### ISSUE TITLE
CoreFoundation +[NSDictionary dictionaryWithObjects:forKeys:count:]

### ISSUE THREAD

**Issue by misterbond** [muxinc/stats-sdk-objc#27]
Hi, we have an issue from our app.
There are crash logs from crashlytics: 
Fatal Exception: NSInvalidArgumentException

> 0  CoreFoundation                 0x184886d8c __exceptionPreprocess
> 1  libobjc.A.dylib                0x183a405ec objc_exception_throw
> 2  CoreFoundation                 0x18481f750 _CFArgv
> 3  CoreFoundation                 0x1847580cc -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
> 4  CoreFoundation                 0x184757f48 +[NSDictionary dictionaryWithObjects:forKeys:count:]
> 5  MUXSDKStats                    0x101163e80 (Missing)
> 6  MUXSDKStats                    0x101163aa4 (Missing)
> 7  MUXSDKStats                    0x101164708 (Missing)
> 8  MUXSDKStats                    0x101164c9c (Missing)
> 9  Foundation                     0x1852152f8 NSKeyValueNotifyObserver
> 10 Foundation                     0x185214e30 NSKeyValueDidChange
> 11 Foundation                     0x185299ca0 NSKeyValueDidChangeWithPerThreadPendingNotifications
> 12 AVFoundation                   0x18a2f706c -[AVPlayerItem didChangeValueForKey:]
> 13 AVFoundation                   0x18a2fab28 -[AVPlayerItem _changeStatusToFailedWithError:]
> 14 AVFoundation                   0x18a30e2d8 __avplayeritem_fpItemNotificationCallback_block_invoke
> 15 libdispatch.dylib              0x184178aa0 _dispatch_call_block_and_release
> 16 libdispatch.dylib              0x184178a60 _dispatch_client_callout
> 17 libdispatch.dylib              0x18418565c _dispatch_main_queue_callback_4CF$VARIANT$mp
> 18 CoreFoundation                 0x18482f070 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
> 19 CoreFoundation                 0x18482cbc8 __CFRunLoopRun
> 20 CoreFoundation                 0x18474cda8 CFRunLoopRunSpecific
> 21 GraphicsServices               0x186731020 GSEventRunModal
> 22 UIKit                          0x18e769758 UIApplicationMain
> 23 Kanopy PROD                    0x100acc408 main (LogExt.swift:18)
> 24 libdyld.dylib                  0x1841ddfc0 start

We don't have a steps to reproduce for this issue. 
Also, this issue occurs on iOS 9-11 versions.
Could you please help resolve this issue. 
Thank you.

**Comment by jsanford8** [comment]
Hey @misterbond - thanks for reporting this. Can you let me know what release version you are using of the integration?

**Comment by misterbond** [comment]
We use Mux-Stats-SDK (0.0.11)

**Comment by wtao-mux** [comment]
@misterbond Can you also attach us a full crash log? Thanks

**Comment by misterbond** [comment]
Yes, sure. Here the full crash logs:
[logs.txt](https://github.com/muxinc/stats-sdk-objc/files/2323555/logs.txt)

**Comment by wtao-mux** [comment]
@misterbond I read into the full log. it appears it was produced by fabric.io's crashlytics. The missing part in the screenshot below stops me from symbolicate the call stack.

<img width="658" alt="screen shot 2018-08-27 at 10 50 46 am" src="https://user-images.githubusercontent.com/37314602/44676102-23ebde00-a9e7-11e8-9e57-4e2e4e65520d.png">
 
Is there anyway you can find the original crash report generated by the OS itself?

**Comment by misterbond** [comment]
I have found only this file:
[Bd1-YfTikZBgQyCB2Uak9F.xccrashpoint.zip](https://github.com/muxinc/stats-sdk-objc/files/2335783/Bd1-YfTikZBgQyCB2Uak9F.xccrashpoint.zip)

**Comment by misterbond** [comment]
Also, I have found a memory leaks from the MUX analytics:
<img width="396" alt="screen shot 2018-08-29 at 8 47 55 pm" src="https://user-images.githubusercontent.com/28996474/44846518-3d945c00-ac59-11e8-83db-9bcfcdd9a92c.png">

**Comment by wtao-mux** [comment]
@misterbond the crash issue has been diagnosed and fixed. Your sdk version is pretty old. we have recently made a major code change. You can go ahead re integrate the latest library. the effort for the new integration should be very minimal. Please seek examples in the https://github.com/muxinc/mux-stats-sdk-avplayer/tree/master/apps repo to see how to do it.

I think the only place of change is in the Podfile. Instead of just one pod, we now have two pods

![screen shot 2018-08-30 at 11 57 26 am](https://user-images.githubusercontent.com/37314602/44873029-f5227180-ac4b-11e8-9b55-640a6ea20b36.png)

**Comment by wtao-mux** [comment]
@misterbond as for the memory leak, i can't reproduce from our side. I am suspecting it is the leak when the app is crashing. So can you provide with us more info regarding the leak?

**Comment by misterbond** [comment]
I just play the video.
I finish the playback.
I'm playing next video.
MUX analytic objects are not deinited.
I think this is a mistake, and at some point when the user plays many movies the app will crash due to memory overflow.

**Comment by misterbond** [comment]
`class MuxAnalytics: NSObject {
    
    static let shared = MuxAnalytics()
    var playerData: MUXSDKCustomerPlayerData? = nil
    
    override init() {
        super.init()
    }
    
    #if os(iOS)
    func send(moviePlayerVC: MoviePlayerVC?, playbackDetails: PlaybackDetailsModel?, currentItem: ItemModel, isBeforePlayback: Bool) {
        guard let playerData: MUXSDKCustomerPlayerData = MUXSDKCustomerPlayerData.init(propertyKey: ConstantsKey.apiKeyForMUXAnalytics) else {return}

        self.playerData = playerData

        let videoData: MUXSDKCustomerVideoData = setup(playbackDetails: playbackDetails, currentItem: currentItem, playerData: playerData, playerName: "iOS Player", isBeforePlayback: isBeforePlayback)

        guard let moviePLayer = moviePlayerVC, let playerLayer = moviePLayer.playerLayer else {return}
        videoData.videoLanguageCode = moviePLayer.player?.accessibilityLanguage

        MUXSDKStats.monitorAVPlayerLayer(playerLayer, withPlayerName: "iOS Player", playerData: playerData, videoData: videoData)
    }
    
    #elseif os(tvOS)
    func send(moviePlayerVC: PlayerVC?, playbackDetails: PlaybackDetailsModel?, currentItem: ItemModel, isBeforePlayback: Bool) {
        guard let playerData: MUXSDKCustomerPlayerData = MUXSDKCustomerPlayerData.init(propertyKey: ConstantsKey.apiKeyForMUXAnalytics) else {return}

        self.playerData = playerData

        let videoData: MUXSDKCustomerVideoData = setup(playbackDetails: playbackDetails, currentItem: currentItem, playerData: playerData, playerName: "tvOS Player", isBeforePlayback: isBeforePlayback)

        guard let moviePLayer = moviePlayerVC else {return}
        videoData.videoLanguageCode = moviePLayer.player?.accessibilityLanguage

        MUXSDKStats.monitorAVPlayerViewController(moviePLayer, withPlayerName: "tvOS Player", playerData: playerData, videoData: videoData)
    }
    #endif
    
    func setup(playbackDetails: PlaybackDetailsModel?, currentItem: ItemModel,playerData: MUXSDKCustomerPlayerData, playerName: String, isBeforePlayback: Bool) -> MUXSDKCustomerVideoData {
        playerData.playerName = playerName
        
        let videoData: MUXSDKCustomerVideoData = MUXSDKCustomerVideoData.init()

        if let playbackDetails = playbackDetails, let isDrmProtected = playbackDetails.isDrmProtected, isDrmProtected {
            if isBeforePlayback {
                videoData.videoStreamType = StreamType.beforePlayback
            } else {
                videoData.videoStreamType = StreamType.hlsDrm
            }
            playerData.experimentName = "DRM-CONTENT"
        } else {
            videoData.videoStreamType = StreamType.hls
        }

        videoData.videoId = currentItem.itemID
        videoData.videoTitle = currentItem.title
        videoData.videoSeries = ""
        videoData.videoProducer = ""
        videoData.videoContentType = ""
        videoData.videoVariantName = ""
        videoData.videoVariantId = ""
        videoData.videoDuration = currentItem.runningTime*1000 as NSNumber
        videoData.videoIsLive = false
        videoData.videoEncodingVariant = ""
        if let playbackDetails = playbackDetails, !isBeforePlayback {
            videoData.videoCdn = "\(playbackDetails.cdn) CDN + \(playbackDetails.serviceName) Storage"
        }
        
        return videoData
    }
    
    func update(playbackDetails: PlaybackDetailsModel?, currentItem: ItemModel, playerName: String) {
        let videoData: MUXSDKCustomerVideoData = MUXSDKCustomerVideoData.init()
        videoData.videoId = currentItem.itemID
        videoData.videoTitle = currentItem.title

        if let playbackDetails = playbackDetails, let isDrmProtected = playbackDetails.isDrmProtected, isDrmProtected {
            videoData.videoStreamType = StreamType.hlsDrm
            if let playerData = self.playerData {
                playerData.experimentName = "DRM-CONTENT"
            }
        } else {
            videoData.videoStreamType = StreamType.hls
        }

        if let playbackDetails = playbackDetails {
            videoData.videoCdn = "\(playbackDetails.cdn) CDN + \(playbackDetails.serviceName) Storage"
        }

        MUXSDKStats.videoChange(forPlayer: playerName, with: videoData)
    }
    
    func destroyPlayer(with name: String) {
        MUXSDKStats.destroyPlayer(name)
        self.playerData = nil
    }
}`

Here our code with Mux analytics if you need.

**Comment by wtao-mux** [comment]
@misterbond thank you for pointing out the memory leak. we have a new release to fix the issue. 
![screen shot 2018-08-31 at 2 44 26 pm](https://user-images.githubusercontent.com/37314602/44938978-dea51480-ad36-11e8-9df9-662480aca630.png).

please Pod update with the latest version
