### ISSUE TITLE
tvOS: Umbrella header for module 'MuxCoreTv' does not include header X

### ISSUE THREAD

**Issue by kyle-fox** [muxinc/stats-sdk-objc#33]
When building for tvOS, Xcode shows these warnings:

```
Umbrella header for module 'MuxCoreTv' does not include header 'MUXSDKAdPlayEvent.h'
Umbrella header for module 'MuxCoreTv' does not include header 'MUXSDKAdThirdQuartileEvent.h'
Umbrella header for module 'MuxCoreTv' does not include header 'MUXSDKAdPlayingEvent.h'
Umbrella header for module 'MuxCoreTv' does not include header 'MUXSDKAdBreakStartEvent.h'
Umbrella header for module 'MuxCoreTv' does not include header 'MUXSDKAdFirstQuartileEvent.h'
Umbrella header for module 'MuxCoreTv' does not include header 'MUXSDKAdRequestEvent.h'
Umbrella header for module 'MuxCoreTv' does not include header 'MUXSDKAdEndedEvent.h'
Umbrella header for module 'MuxCoreTv' does not include header 'MUXSDKAdMidpointEvent.h'
Umbrella header for module 'MuxCoreTv' does not include header 'MUXSDKAdPauseEvent.h'
Umbrella header for module 'MuxCoreTv' does not include header 'MUXSDKAdBreakEndEvent.h'
Umbrella header for module 'MuxCoreTv' does not include header 'MUXSDKAdResponseEvent.h'
Umbrella header for module 'MuxCoreTv' does not include header 'MUXSDKAdErrorEvent.h'
```

It looks like the warning is because [MuxCoreTv.h](https://github.com/muxinc/stats-sdk-objc/blob/master/Frameworks/tvOS/fat/MuxCoreTv.framework/Headers/MuxCoreTv.h) does not import these files, but they are still included in the framework itself. I was going to open a PR, but I'm not sure whether it's preferable to include these files in the header or remove the Ad related headers from being included in the tvOS version of the framework, so I'll leave that to you all 😄

**Comment by jsanford8** [comment]
Thanks Kyle! We'll take a look at this

**Comment by nidhik** [comment]
Closing as we have moved to using the XCFramework bundle type as of the following releases:
* https://github.com/muxinc/mux-stats-sdk-avplayer/releases/tag/v2.0.0
* https://github.com/muxinc/stats-sdk-objc/releases/tag/v3.0.0
