### ISSUE TITLE
Nullability warnings

### ISSUE THREAD

**Issue by jpstuehler** [muxinc/stats-sdk-objc#7]
I've just implemented your SDK and it went really well. I've only got some warning in Xcode 8.3.3 about the nullability annotations which are supposed to be `nonnull` instead of `nullable`:

```
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
```

This applies to MUXSDKCustomerPlayerData as well as MUXSDKStats.

On another note. It seems like MUXSDKQueryData is expose but can't really be used with the rest of the API so it could as well be omitted from the public API.

**Comment by theRealWardo** [comment]
Thanks for reporting these @jpstuehler! I'll clean these up in our next release. If you have any other feature requests or recommendations on how we could make things better please reach out!

**Comment by jpstuehler** [comment]
Yes, thank you!
